#  Let's Play Scrabble! 

alph = 'abcdefghijklmnopqrstuvwxyz'
main = 'TQSBAODTTABMRUHDKNVUORAKATOZLFBFDWPHQLANSZIKOSEDESXZLDYEUBJRROAVZRBSLWESCEGGOCEMLFMAHAYSRNMCXATHGNZQBCLSCEMKIVELCRXCJTBBTXGBRNDQTLJMLUOEQWTHWVBAZHAABXPZELKBNWSNCZLNSBELFFKDLVFWOWNDQWMLFXEQWAQOQRIAAVSXAADYEUUAMTHYLSCVILMNE'
s = '**************************'
word = 'FLAGHYPHEN'